apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.template.yml: |
    _format_version: "3.0"

    services:
      - name: users-api
        url: http://users-api
        routes:
          - name: users-route
            paths:
              - /users

      - name: catalog-api
        url: http://catalog-api
        routes:
          - name: catalog-route
            paths:
              - /catalog
              - /games
        plugins:
          - name: jwt

    consumers:
      - username: games-client

    jwt_secrets:
      - consumer: games-client
        key: GamesStore.API
        algorithm: HS256
        secret: "$JWT_SECRET_KEY"
