apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      initContainers:
        - name: inject-secrets
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              apk add --no-cache gettext
              envsubst < /config-template/kong.template.yml > /kong/kong.yml
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: kong-final-config
              mountPath: /kong
      containers:
        - name: kong
          image: kong:3.6
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: kong-final-config 
              mountPath: /kong
      volumes:
        - name: config-template
          configMap:
            name: kong-config
        - name: kong-final-config
          emptyDir: {}
