apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: fcg/rabbitmq
        property: username
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: fcg/rabbitmq
        property: password
